### ISSUE TITLE
System log entry: "dsi_stream_read: len:0, unexpected EOF" (non-critical)

### ISSUE THREAD

**Issue by friedrichromstedt** [Netatalk/netatalk#1631] opened 2024-10-14 14:57 UTC
# Software of the Servers and the Clients

This is with `netatalk-4.0.1`. The behaviour reported here is present since `3.x` releases, but I didn't track it before.

- **Servers**: `Arch Linux 6.11.3` 64-bit and `Arch Linux 6.10.10` 32-bit.
- **Clients**: macOS 10.11 and macOS 10.14.

# Description of the Observed Behaviour

Under *certain conditions* (see below) the following system log entry shows up:
```
dsi_stream_read: len:0, unexpected EOF
```
There are a few issues reporting the same: #82 and #302. However, this is not impeding functionality here. I am opening a new issue, since the severity is thus considerably smaller in my case, compared to those other related issues.

# Reproduction of the Error

The error can be reproduced reliably by acting on a client in the following manner:

1. Open a Finder window, navigate to the server's entry in the side bar.
2. Connect.
3. Immediately after having connected, disconnect (i.e., do *not* mount any of the shares presented).

The following amended procedure on the client side leads to a slighly diverging log, where the error line is *not* presented anymore:

1. (as above)
2. (as above)
3. Mount any of the shares.
4. Disconnect from the server.

# Logs

The behaviour is completely identical (literally, up to traffic figures) for the 10.11 and the 10.14 clients. There are some subtle differences for the two servers.

Each log is produced by first provoking the error message, and after that by following the amended way of use on the client side which avoids it.

## Arch Linux (32-bit)

Here's the log for one of the Arch machines (it is the 32-bit machine):
```
Command: journalctl -fn0

> Connecting, but not mounting:
Oct 14 15:38:36 wserver afpd[12309]: pam_unix(netatalk:session): session opened for user friedrich(uid=1000) by (uid=0)
Oct 14 15:38:36 wserver afpd[12309]: Login by friedrich (AFP3.4)
> Disconnecting:
Oct 14 15:38:38 wserver afpd[12309]: AFP logout by friedrich
Oct 14 15:38:38 wserver afpd[12309]: dsi_stream_read: len:0, unexpected EOF
Oct 14 15:38:38 wserver afpd[12309]: afp_over_dsi: client logged out, terminating DSI session
Oct 14 15:38:38 wserver afpd[12309]: pam_unix(netatalk:session): session closed for user friedrich
Oct 14 15:38:38 wserver afpd[12309]: AFP statistics: 0.67 KB read, 0.52 KB written via DSI
> Disconnected.
> Connecting:
Oct 14 15:38:52 wserver afpd[12316]: pam_unix(netatalk:session): session opened for user friedrich(uid=1000) by (uid=0)
Oct 14 15:38:52 wserver afpd[12316]: Login by friedrich (AFP3.4)
> Mounting.
> Disconnecting:
Oct 14 15:38:56 wserver afpd[12316]: AFP logout by friedrich
Oct 14 15:38:56 wserver afpd[12316]: pam_unix(netatalk:session): session closed for user friedrich
Oct 14 15:38:56 wserver afpd[12316]: AFP statistics: 1.84 KB read, 12.15 KB written via DSI
Oct 14 15:38:56 wserver afpd[12316]: done
> Disconnected.
```

## Arch Linux (64-bit)

And here's the log produced by the other Arch Linux machine (the 64-bit one):
```
Command: journalctl -fn0

> Connecting, but not mounting:
Oct 14 15:50:09 T470p afpd[12747]: pam_systemd_home(netatalk:auth): New sd-bus connection (system-bus-pam-systemd-home-12747) opened.
Oct 14 15:50:09 T470p afpd[12747]: pam_unix(netatalk:session): session opened for user friedrich(uid=1000) by (uid=0)
Oct 14 15:50:09 T470p afpd[12747]: Login by friedrich (AFP3.4)
> Disconnecting:
Oct 14 15:50:13 T470p afpd[12747]: AFP logout by friedrich
Oct 14 15:50:13 T470p afpd[12747]: dsi_stream_read: len:0, unexpected EOF
Oct 14 15:50:13 T470p afpd[12747]: afp_over_dsi: client logged out, terminating DSI session
Oct 14 15:50:13 T470p afpd[12747]: pam_unix(netatalk:session): session closed for user friedrich
Oct 14 15:50:13 T470p afpd[12747]: AFP statistics: 0.75 KB read, 0.62 KB written via DSI
> Connecting:
Oct 14 15:50:21 T470p afpd[12761]: pam_systemd_home(netatalk:auth): New sd-bus connection (system-bus-pam-systemd-home-12761) opened.
Oct 14 15:50:21 T470p afpd[12761]: pam_unix(netatalk:session): session opened for user friedrich(uid=1000) by (uid=0)
Oct 14 15:50:21 T470p afpd[12761]: Login by friedrich (AFP3.4)
> Mounting.
> Disconnecting:
Oct 14 15:50:32 T470p afpd[12761]: AFP logout by friedrich
Oct 14 15:50:32 T470p afpd[12761]: pam_unix(netatalk:session): session closed for user friedrich
Oct 14 15:50:32 T470p afpd[12761]: AFP statistics: 2.19 KB read, 12.85 KB written via DSI
Oct 14 15:50:32 T470p afpd[12761]: done
> Disconnected.
```

**Comment by rdmark** [comment] 2024-10-14 16:18
Thanks for filing the issue report with reproduction steps and logs. 

Another example with several user testimonials is this SourceForge bug: https://sourceforge.net/p/netatalk/bugs/636/

Needless to say, this bug has been around for a long time, but in line with your observation I haven't seen proof in recent years that it causes actual data loss anymore. Still, it's not ideal to have unexpected fail states occurring at a regular basis. Do you have a patch in mind that could improve this?

**Comment by singular0** [comment] 2024-10-14 18:33
@friedrichromstedt Could you please try to reproduce the same error with `log level = maxdebug` in `/etc/afp.conf`?

**Comment by NJRoadfan** [comment] 2024-10-23 02:04
I figured out what might be causing this problem. It has to do with the FPLogout command sent by a client. Sometimes macOS adds an additional 0 byte to the FPLogout packet triggering the error. As per Apple's AFP3.3 documentation, this extra null byte is part of the specification. It was NOT part of the original AFP2.0 specification described in "Inside AppleTalk" (page 13-109), which is what Netatalk is likely following.

**Comment by NJRoadfan** [comment] 2024-10-23 02:36
The bug seems to be how `dsi_stream_read()` function's error handling. It throws the error only when total data transferred for the session is less then one kilobyte of data.

**Comment by NJRoadfan** [comment] 2024-10-23 23:44
https://github.com/Netatalk/netatalk/blob/3ec8a4d5b687bb5deb88db4175e91310b3e0b612/libatalk/dsi/dsi_stream.c#L502

Change this to:
`if (!(dsi->flags & DSI_DISCONNECTED || dsi->flags & DSI_AFP_LOGGED_OUT) ) {`

Clearly at the point the error is being thrown, the client has logged out, so this can be safely ignored. The comments in the code clearly indicate this was a problem. So it likely broke later on when this code was refactored and never fixed. Pretty much all logs I can find with this error online show it occurring with less then 1kb of data read and after an immediate logoff of a client.

This other bug that triggered this warning involved extended attributes and has long since been fixed.

**Closed** 2024-10-24 05:54 UTC
