### ISSUE TITLE
netatalk2: Out of tree builds broken

### ISSUE THREAD

**Issue by VorpalBlade** [Netatalk/netatalk#408] opened 2023-08-22 09:00 UTC
If you try to build netatalk 2.x out of tree, some of the config files are missing.

E.g:

```bash
mkdir build && cd build
../netatalk-2.2.10/configure [...]
make
make install
```

Then all of these will be missing:
* /etc/netatalk/AppleVolumes.system
* /etc/netatalk/afp_ldap.conf
* /etc/netatalk/netatalk.conf
* /etc/netatalk/atalkd.conf
* /etc/netatalk/papd.conf

I'm not an expert at automake/autoconf (I have avoided them for over a decade, having moved over to cmake and other newer build systems for my own things), so I don't know exactly what is wrong here. Presumably something is set to relative the build dir instead of the source dir by mistake.

**Comment by rdmark** [comment] 2023-08-22 19:11
Good catch! Do they end up anywhere else on the file system, by any change? Any other files that don't get installed properly, or only these five?

Maybe something like $DESTDIR isn't expanded properly somewhere... Not obvious what's wrong from a read of the makefiles.

**Comment by VorpalBlade** [comment] 2023-08-23 17:25
> Good catch! Do they end up anywhere else on the file system, by any change?

No, I think they are just gone

> Any other files that don't get installed properly, or only these five?

Didn't really look into it. Would be quite easy though: make install with `DESTDIR` two different builds and diff the results.

**Comment by rdmark** [comment] 2023-08-26 00:15
I think the problem is that automake doesn't copy the config files into the build dir (unless I misunderstand the mechanism).

For the record, this affects netatalk3 as well.

**Comment by rdmark** [comment] 2023-08-26 03:02
Found the fix. You were right: a missing $(srcdir) prefix was the culprit. The bug was fixed in netatalk3 in March of 2012 but not ported to netatalk2, which was the norm back then.

PR in https://github.com/Netatalk/netatalk/pull/421 -- please give it a spin!

**Comment by rdmark** [comment] 2023-08-26 03:18
As a side note, I think this is a bug that we want `make distcheck` to catch in the future. The mechanism of the distcheck target is to do an out of tree build and installation into a temporary dir. I wonder if some flag need to be set for it to stop when it encounters a missing file.

The logs from a distcheck pre-patch does say there's an error but happy chugs along. This isn't right I think.
```
for f in AppleVolumes.system netatalk.conf afp_ldap.conf atalkd.conf papd.conf afpd.conf AppleVolumes.default; do \
        if test "xno" = "xyes" -o ! -f /home/dmark/dev/netatalk2/netatalk-2.2.10dev/_inst/etc/netatalk/$f; then \
                echo "/usr/bin/install -c -m 644 $f /home/dmark/dev/netatalk2/netatalk-2.2.10dev/_inst/etc/netatalk"; \
                /usr/bin/install -c -m 644 $f /home/dmark/dev/netatalk2/netatalk-2.2.10dev/_inst/etc/netatalk; \
        else \
                echo "not overwriting $f"; \
        fi; \
done
/usr/bin/install -c -m 644 AppleVolumes.system /home/dmark/dev/netatalk2/netatalk-2.2.10dev/_inst/etc/netatalk
/usr/bin/install: cannot stat 'AppleVolumes.system': No such file or directory
/usr/bin/install -c -m 644 netatalk.conf /home/dmark/dev/netatalk2/netatalk-2.2.10dev/_inst/etc/netatalk
/usr/bin/install: cannot stat 'netatalk.conf': No such file or directory
/usr/bin/install -c -m 644 afp_ldap.conf /home/dmark/dev/netatalk2/netatalk-2.2.10dev/_inst/etc/netatalk
/usr/bin/install: cannot stat 'afp_ldap.conf': No such file or directory
/usr/bin/install -c -m 644 atalkd.conf /home/dmark/dev/netatalk2/netatalk-2.2.10dev/_inst/etc/netatalk
/usr/bin/install: cannot stat 'atalkd.conf': No such file or directory
/usr/bin/install -c -m 644 papd.conf /home/dmark/dev/netatalk2/netatalk-2.2.10dev/_inst/etc/netatalk
/usr/bin/install: cannot stat 'papd.conf': No such file or directory
/usr/bin/install -c -m 644 afpd.conf /home/dmark/dev/netatalk2/netatalk-2.2.10dev/_inst/etc/netatalk
/usr/bin/install -c -m 644 AppleVolumes.default /home/dmark/dev/netatalk2/netatalk-2.2.10dev/_inst/etc/netatalk
if test "x" != "x"; then \
        if ! test -d "x"; then \
                mkdir -p ""; \
        fi; \
        cd ""; \
        wget http://prdownloads.sourceforge.net/webadmin/webmin-.tar.gz ; \
        tar xzf webmin-.tar.gz; \
        rm webmin-.tar.gz; \
        /etc/init.d/webmin stop; \
        rm -r webmin; \
        mv webmin- webmin; \
        cd webmin; \
[...]
```

**Comment by VorpalBlade** [comment] 2023-08-26 16:18
This seems to work. I also diffed two packages (one in tree the other out of tree) and there are no differing files.

There are however differences in the compiled binaries, which is strange. So, the builds are not fully reproducible, though that is a certainly a separate issue.

**Comment by VorpalBlade** [comment] 2023-08-26 16:29
It seems the issue with different binaries stems from embedded paths in the binaries (probably from `__FILE__` in `logger.h`) which uses relative paths like `../../../../netatalk-2.2.10/libatalk/cnid/cdb/cnid_cdb_delete.c` vs just `cnid_cdb_delete.c`. Benign and not sure if it is worth (or possible) to try to do something about it.

Then there is a lot of assembly changes related to offsets of loads, stores and calls, probably due to changes in the string lengths in `.rodata` due to the aformentioned issue.

**Comment by rdmark** [comment] 2023-08-26 18:10
Excellent binary sleuthing! I do know for a fact that the logger routines in netatalk2 are quirky. They overhauled the logging in netatalk3. I have a long term plan to forward-port all of the AppleTalk stuff back into netatalk3+ so I think it's ok to no make further improvements to this aspect of netatalk2 right now.

**Comment by VorpalBlade** [comment] 2023-08-26 18:36
> Excellent binary sleuthing!

[diffoscope](https://diffoscope.org/) has made this so much easier in recent years.

**Comment by rdmark** [comment] 2023-08-26 19:04
Force pushed a change now with an extra test for existence of the static origin config file. It might be worth going over the Makefiles and do similar improvements elsewhere (since make distcheck seems a bit lenient with errors)

**Comment by rdmark** [comment] 2023-08-27 04:03
I poked around and tested the other static files, f.e. static man pages, and automake all handles their absences correctly (throw errors). I think the config/Makefile situation is unique since it does some shell script trickery to handle the overwrite option, rather than the proper automake hooks used elsewhere.

Also, no change is needed in netatalk3 after all. For some reason the distcheck handles the error case correctly and I'm not sure why.

**Closed** 2023-08-27 16:29 UTC
Labels: target-release-2.2
