### ISSUE TITLE
Netatalk logs with microsecond time stamps when using "log file" option

### ISSUE THREAD

**Issue by hnagasawa** [Netatalk/netatalk#580] opened 2023-12-12 02:39 UTC
netatalk.log is recorded down to the millisecond.
Example: 16:22:39.963659
I would like netatalk to record this as 16:22:39. Is there a way?
environment
RockLinux9.3(x86_64)
Netatalk netatalk-3.1.18-1.el9.x86_64
(Installed with dnf command)

**Comment by rdmark** [comment] 2023-12-13 06:03
@hnagasawa May I ask how you use the netatalk log data? I’m wondering if you’re able to filter the log output with `sed` for example, to strip the milliseconds from the output. 

To my best knowledge there is no way to change the log time stamp format during runtime.

**Comment by hnagasawa** [comment] 2023-12-13 06:21
@rdmark  I'm trying to collect access logs of users who access Netatalk using a software called alog converter.
(Alog converter is a software that collects access logs. Samba access logs can be collected with alog converter.)Alog converter support says that access logs cannot be imported unless the milliseconds are output.

**Comment by rdmark** [comment] 2023-12-13 11:03
@hnagasawa I understand your use case now. Thank you. 

Would you be able to share a few lines of your logs so that I understand exactly the format that you are seeing?

When I looked at my own notes the syslogs that I get from netatalk looked like this:

```
Aug 08 05:06:11 buntu afpd[157327]: ad_entry_check_size(): overflow off 354 required_len 16 bufsize 0
```

So I don't see milliseconds being recorded in my environment (Ubuntu).

**Comment by hnagasawa** [comment] 2023-12-13 11:32
@rdmark 
/var/log/netatalk/natatalk.log (RockLinux9.3 netatalk-3.1.18-1.el9.x86_64)

Dec 08 15:59:35.402141 afpd[15348] {dsi_tcp.c:239} (info:DSI): AFP/TCP session f
rom 192.168.1.157:50684
Dec 08 15:59:35.404921 afpd[15264] {main.c:151} (info:AFPDaemon): child[15348]:
done
Dec 08 15:59:35.405051 afpd[15351] {dsi_tcp.c:239} (info:DSI): AFP/TCP session f
rom 192.168.1.157:50685
Dec 08 15:59:35.407424 afpd[15264] {main.c:151} (info:AFPDaemon): child[15351]:
done
Dec 08 15:59:37.433933 afpd[15354] {dsi_tcp.c:239} (info:DSI): AFP/TCP session f
rom 192.168.1.157:50687
Dec 08 15:59:37.436926 afpd[15355] {dsi_tcp.c:239} (info:DSI): AFP/TCP session f
rom 192.168.1.157:50688
Dec 08 15:59:37.439287 afpd[15264] {main.c:151} (info:AFPDaemon): child[15354]:
done
Dec 08 15:59:37.439362 afpd[15264] {main.c:151} (info:AFPDaemon): child[15355]:
done

Please let me know if you need any other information.

I will try Netatalk under Ubuntu 14-Dec-2023. (Here is Japan. Now 20:32 )

**Comment by rdmark** [comment] 2023-12-13 12:29
Is this the Linux distribution that you are using? https://rockylinux.org/news/rocky-linux-9-3-ga-release/

This article talks about altering the precision of log datestamps using /etc/rsyslog.conf

https://askubuntu.com/questions/783113/how-to-include-millisecond-in-syslogs#783115

The article is for Ubuntu but I think rsyslog works basically the same on Fedora based distros.

**Comment by hnagasawa** [comment] 2023-12-13 14:26
> Is this the Linux distribution that you are using? https://rockylinux.org/news/rocky-linux-9-3-ga-release/

Yes

I'll try tomorrow. It's now midnight in Japan

**Comment by hnagasawa** [comment] 2023-12-14 05:02
@rdmark

I tried to netatalk under Ubuntu22.04LST.
I edit afp.conf, I add line Gobal "log file = /var/log/netatalk/netatalk.log"
and I restart netatalk service.
I check netatalk.log I found msecond in netatalk.log file.
I delete /var/log/netatalk/netatalk.log line in afp.conf and I restart netatalk service.
Netatalk log wirite in /var/log/syslog file.
It does not msecond.

**Comment by rdmark** [comment] 2023-12-14 14:03
Good catch, I can reproduce what you're seeing in the latest `main` branch code as well.

I don't think it's correct that the time stamps are using milliseconds when redirecting logs to a file using the "log file" option. Let me research if this was deliberate design decision or a mistake made a long time ago.

**Comment by hnagasawa** [comment] 2023-12-15 00:11
rdmark

This phenomenon occurs on CentOS7-9, RockyLinux8,9, and Ubuntu22.04LST as far as I tested.

**Comment by hnagasawa** [comment] 2023-12-15 04:28
@rdmark 
Reference information from RHEL(How to configure rsyslog in high precision (millisecond) mode)
------------------------------------------------------------------
How to configure rsyslog in high precision (milliseconds) mode

1) Update /etc/rsyslog.conf

    Search for the following line:

For RHEL 8,9:

module(load="builtin:omfile" Template="RSYSLOG_TraditionalFileFormat")

    Change it to:
For RHEL 8,9:

module(load="builtin:omfile" Template="RSYSLOG_FileFormat")

    Save and close the file.

2) Restart rsyslog service.


    For RHEL 7,8,9

# systemctl restart rsyslog

3) Check logs on the system.

# logger test

2013-01-22T16:43:16.990159-05:00 VM6.2server root: test

Notice that the "16:43:16.990159" now contains 6 digits after "16:43:16."

    This information is available from /usr/share/doc/rsyslog-*/rsyslog_conf_templates.html:


RSYSLOG_FileFormat - a modern-style logfile format similar to TraditionalFileFormat, buth with high-precision timestamps and timezone information.
-----------------------------------------------------------------------------------------------

rsyslog.conf in RockyLinux9.3 is configured with module(load="builtin:omfile" Template="RSYSLOG_TraditionalFileFormat").

Isn't the log output by Netatalk not affected by this module in rsyslog.conf if we specify the log output destination as /var/log/netatalk/netatalk.log in the afp.conf settings?

**Comment by rdmark** [comment] 2023-12-15 08:36
A code deep dive revealed that this was a deliberate choice made in 2009: https://github.com/Netatalk/netatalk/commit/41b1402c02068d42dc6b50426812fdbd4f4a460f

I searched through the old mailing list archives and bug tracker, but can't find a record of the reasoning for this change. My only guess would be that someone needed it for very fine-grained performance profiling at the time.

Let me send a Request for Comment to the netatalk community to hear if anyone is relying on the microsecond granularity logging. If noone objects I will revert the above change in a week's time.

**Comment by hnagasawa** [comment] 2023-12-15 08:50
@rdmark 
Please let me know if you decide to revert the above change.

**Comment by rdmark** [comment] 2023-12-15 09:00
For the record, I believe this is the tool that doesn't like microsecond accuracy time stamps in logs: https://www.amiya.co.jp/english/solutions/alog/

**Comment by slowfranklin** [comment] 2023-12-15 09:10
On 12/15/23 09:36, Daniel Markstedt wrote:
> Let me send a Request for Comment to the netatalk community to hear if 
> anyone is relying on the microsecond granularity logging. If noone 
> objects I will revert the above change in a week's time.

sorry, but nack. This is required for debugging.

Afair when logging to syslog we don't log without microseconds 
granularity, maybe the OP can use this.

If anyone feels like it, we could have an option that makes this 
behaviour configurable

-slow

**Comment by hnagasawa** [comment] 2023-12-15 09:23
@sloowfranklin 
This tool (converter) doesn't like microsecond accuracy time stamps in logs
>If anyone feels like it, we could have an option that makes this
>behaviour configurable

Is netatalk the option you mention? Is it RockLinux? Or is it an Alog converter?

If Alog converter, Alog converter does not have option

**Comment by rdmark** [comment] 2023-12-15 09:31
@slowfranklin If going down the configurability route, would you recommend making it a compile time or run time option?

**Comment by rdmark** [comment] 2023-12-15 09:32
For the record, this is the patch that's needed to drop microseconds from the logs:

```
diff --git a/libatalk/util/logger.c b/libatalk/util/logger.c
index 402b532b..db5c914a 100644
--- a/libatalk/util/logger.c
+++ b/libatalk/util/logger.c
@@ -126,7 +126,7 @@ static int generate_message(char **message_details_buffer,
     char buf[256];

     gettimeofday(&tv, NULL);
-    strftime(buf, sizeof(buf), "%b %d %H:%M:%S.", localtime(&tv.tv_sec));
+    strftime(buf, sizeof(buf), "%b %d %H:%M:%S", localtime(&tv.tv_sec));
     pid = getpid();
     const char *basename = strrchr(log_src_filename, '/');
     if (basename) {
@@ -137,9 +137,8 @@ static int generate_message(char **message_details_buffer,


     len = asprintf(&details,
-                   "%s%06u %s[%d] {%s:%d} (%s:%s): %s\n",
+                   "%s %s[%d] {%s:%d} (%s:%s): %s\n",
                    buf,
-                   (int)tv.tv_usec,
                    log_config.processname,
                    pid,
                    basename,
```

**Comment by slowfranklin** [comment] 2023-12-15 09:34
On 12/15/23 10:31, Daniel Markstedt wrote:
> @slowfranklin <https://github.com/slowfranklin> If going down the 
> configurability route, would you recommend making it a compile time or 
> run time option?

runtime.

**Comment by hnagasawa** [comment] 2023-12-15 11:11
@rdmark 
Are you planning to fix netatalk with runtime options? Please let me know when you decide.

**Comment by rdmark** [comment] 2023-12-15 13:25
A proposed changeset that introduce a "log seconds" option: https://github.com/Netatalk/netatalk/pull/583

Use like this to log to file with second instead of microsecond time stamps.
```
[Global]
; Global server settings
log file = /var/log/netatalk/netatalk.log
log seconds = yes
```

**Comment by hnagasawa** [comment] 2023-12-15 15:13
@rdmark 
Please tell me, when your debug new version,

**Comment by rdmark** [comment] 2023-12-16 10:07
@hnagasawa Are you able to compile netatalk from source code? Rocky Linux is Fedora based so all development packages should be available from the package manager.

**Comment by rdmark** [comment] 2023-12-17 13:02
The patch has been merged to the `main` branch, so let me close this ticket.

I will write a wiki document for how to compile netatalk v3 on Fedora tomorrow.

**Closed by rdmark** 2023-12-17 13:02 UTC

**Comment by rdmark** [comment] 2023-12-18 13:56
@hnagasawa Here is a wiki page with instructions how to compile on Fedora 39. https://github.com/Netatalk/netatalk/wiki/Installing-Netatalk-3-on-Fedora

For now, please remove the `--with-tracker-pkgconfig-version=3.0` parameter when running ./configure. There is a bug right now makes Spotlight not compile on Fedora.

**Comment by hnagasawa** [comment] 2023-12-19 00:12
@rdmark 
Thank you. I will try under RockyLinux9.3.

**Comment by hnagasawa** [comment] 2023-12-19 07:27
@rdmark 
I compiled successfully under RockyLinux9.3.

# /usr/local/sbin/afpd -V
afpd 3.1.99dev - Apple Filing Protocol (AFP) daemon of Netatalk

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version. Please see the file COPYING for further information and details.

afpd has been compiled with support for these features:

          AFP versions: 2.2 3.0 3.1 3.2 3.3 3.4
         CNID backends: dbd last
      Zeroconf support: Avahi
  TCP wrappers support: No
   Admin group support: Yes
    Valid shell checks: Yes
      cracklib support: Yes
            EA support: ad | sys
           ACL support: Yes
          LDAP support: Yes
         D-Bus support: Yes
     Spotlight support: No
         DTrace probes: Yes

              afp.conf: /usr/local/etc/afp.conf
           extmap.conf: /usr/local/etc/extmap.conf
       state directory: /usr/local/var/netatalk/
    afp_signature.conf: /usr/local/var/netatalk/afp_signature.conf
      afp_voluuid.conf: /usr/local/var/netatalk/afp_voluuid.conf
       UAM search path: /usr/local/lib/netatalk/
  Server messages path: /usr/local/var/netatalk/msg/

But same issue occured.

afp.conf

[Global]
; Global server settings
 mac charset = MAC_JAPANESE
 ;uam list = uams_clrtxt.so uams_dhx.so uams_dhx2.so uams_guest.so
 afpstats = yes
 log level = default:info
# log file = /var/log/netatalk/netatalk.log
 log file = /var/log/syslog
 log seconds = yes
 vol dbpath = /var/netatalk/CNID
 vol preset = my_default_values

Dec 19 16:16:53.101138 afpd[983] {status.c:631} (info:AFPDaemon): signature is B058973E0349085A35570476CB8A843F
Dec 19 16:16:53.110724 afpd[983] {auth.c:111} (info:AFPDaemon): uam: "DHX2" available
Dec 19 16:16:53.110770 afpd[983] {auth.c:111} (info:AFPDaemon): uam: "DHCAST128" available
Dec 19 16:16:53.110779 afpd[983] {status.c:359} (info:AFPDaemon): servername: RockyLinux
Dec 19 16:16:53.110814 afpd[983] {afp_config.c:196} (note:AFPDaemon): Netatalk AFP/TCP listening on 192.168.1.245:548
Dec 19 16:16:53.110830 afpd[983] {ldap_config.c:103} (info:AFPDaemon): LDAP: not used
Dec 19 16:16:53.110845 afpd[983] {cnid.c:55} (info:AFPDaemon): Registering CNID module [last]
Dec 19 16:16:53.110849 afpd[983] {cnid.c:55} (info:AFPDaemon): Registering CNID module [dbd]
Dec 19 16:16:53.361034 netatalk[981] {afp_avahi.c:94} (info:AFPDaemon): hostname: RockyLinux
Dec 19 16:16:53.361316 netatalk[981] {afp_avahi.c:118} (info:AFPDaemon): Registering server 'RockyLinux' with Bonjour
