### ISSUE TITLE
Build issue with system talloc

### ISSUE THREAD

**Issue by dharanlinux** [Netatalk/netatalk#555] opened 2023-11-09 07:04 UTC
Hi Team,

   I am trying to build the 3.1.18 with the configuration of '--with-talloc=no' to use the system installed talloc instead of bundled one and facing the below issue.

```
bin/ld: afpd-spotlight_marshalling.o: undefined reference to symbol 'talloc_named_const@@TALLOC_2.0.2'
usr/local/lib/libtalloc.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:603: afpd] Error 1
``` 

After adding the `@TALLOC_LIBS@` into `afpd_LDADD` into netatalk-3.1.18/etc/afpd/Makefile.am, fixing the build issue. Is this correct fix?

vi netatalk-3.1.18/etc/afpd/Makefile.am

```
afpd_LDADD =  \
	$(top_builddir)/libatalk/libatalk.la \
-	@LIBGCRYPT_LIBS@ @QUOTA_LIBS@ @WRAP_LIBS@ @LIBADD_DL@ @ACL_LIBS@ @PTHREAD_LIBS@ @GSSAPI_LIBS@ @KRB5_LIBS@ @MYSQL_LIBS@
+	@LIBGCRYPT_LIBS@ @QUOTA_LIBS@ @WRAP_LIBS@ @LIBADD_DL@ @ACL_LIBS@ @PTHREAD_LIBS@ @GSSAPI_LIBS@ @KRB5_LIBS@ @MYSQL_LIBS@ @TALLOC_LIBS@
```

**Comment by dgsga** [comment] 2023-11-09 18:35
Thanks for spotting this @dharanlinux. Fixed in #556

**Comment by rdmark** [comment] 2023-11-09 22:35
@dharanlinux Just out of curiosity, which OS distro and version are you using?

**Closed** 2023-11-10 09:33 UTC

**Comment by UUVE** [comment] 2023-11-15 16:44
I can confirm this exact issue in debian, where I've build a package  for netatalk 3.1.18 for the lates OS release bookworm, following the configuration for previous package (3.1.12) available for debian Buster. My fix was to add LDFLAGS=-ltalloc in the config target  in debian/rules. Another thing I've noted is that Debian bookworm miss the shared libraries libtracker-sparql-2.0-dev (it provides instead libtracker-sparql-3.0-dev) and libtracker-miner-2.0-dev (completely missed).
I also continue to experiment segmentation faults with dbd -c and malformed apple double files coming from a reinstallation 
of a backup of files once served by netatalk 2.2.x and then by netatalk 3.1.2, but this is a story for another post in current (or past, but yet unresolved?) issues.

**Comment by UUVE** [comment] 2023-11-15 16:48
Sorry very much, I've missed that this issue was resolved

**Comment by rdmark** [comment] 2023-11-15 23:08
@UUVE Can you please file a new issue ticket for your segfault in `dbd` and include as much context as possible?

As for tracker-sparql libs in Debian: this is expected since they have transitioned to the v3.0 release series for that software. We updated our own documentation some time ago, but please let us know if something still references v2.0 tracker libs.
