### ISSUE TITLE
netatalk2: Header file at.h conflict with glibc

### ISSUE THREAD

**Issue by VorpalBlade** [Netatalk/netatalk#409] opened 2023-08-22 09:25 UTC
When creating a package for netatalk2 for Arch Linux I ran into an interesting conflict:

```
netatalk2: /usr/include/netatalk/at.h exists in filesystem (owned by glibc)
```

It seems glibc has a conflicting version of this already:
```c
// [Some comments elided here]
#ifndef _NETATALK_AT_H
#define _NETATALK_AT_H 1

#include <asm/types.h>
#include <bits/sockaddr.h>
#include <linux/atalk.h>
#include <sys/socket.h>

#define SOL_ATALK       258     /* sockopt level for atalk */

#endif	/* netatalk/at.h */
```

netatalk 2.x installs a completely different header that doesn't define `SOL_ATALK`, but does define many other things. I don't see a way of reconciling this, as Arch Linux does not allow packages to have conflicting files.

I don't personally plan to build any software on top of netatalk so I will simply rename the file, but this would break any downstream dependencies (if any exist).

**Comment by rdmark** [comment] 2023-08-22 21:29
Incidentally, I have been tinkering with Debian deb packaging recently and ran into the same thing. In the historical 2.x deb they have had a distribution exclusion rule for at.h in place, probably in place for decades.

A quick mailing list archive search gave me this: https://sourceforge.net/p/netatalk/mailman/netatalk-devel/thread/20010525092140.A1223%40jroger.in-berlin.de/#msg5316399

So the conclusion is: If on Linux, use glibc at.h. If on any other OS that doesn't come with glibc, use netatalk at.h

I would be inclined to keep the status quo of letting Linux packaging managers exclude at.h at their discretion. Do you have other suggestions how we can gracefully do better upstream, though?

**Comment by rdmark** [comment] 2023-08-23 16:48
As a side note, another legacy naming conflict exists with `uniconv`. The X Window editor Yudit distributes an executable with exactly the same name: https://manpages.ubuntu.com/manpages/xenial/man1/uniconv.1.html

The Debian deb packaging script renames our executable and man page to `netatalk-uniconv`

**Comment by VorpalBlade** [comment] 2023-08-23 17:21
> I would be inclined to keep the status quo of letting Linux packaging managers exclude at.h at their discretion. Do you have other suggestions how we can gracefully do better upstream, though?

Probably you don't want make install to install it if on Linux. What if a user runs make install directly and overwrites the file? (They should be installing to `/usr/local`, sure, but you never know).

**Comment by rdmark** [comment] 2023-08-23 19:04
How about this for a solution: https://github.com/Netatalk/netatalk/pull/414

I haven't actually tested that it works as intended yet, hence in draft state.

**Comment by rdmark** [comment] 2023-08-23 19:06
Checking for glibc might be an even more sophisticated option, if it is possible with autoconf.

**Comment by VorpalBlade** [comment] 2023-08-23 19:51
I don't have any options using musl on Linux. Presumably you could try Alpine in docker to determine if it also ships an at.h. Other than that it seems like checking for Linux should be enough

**Comment by rdmark** [comment] 2023-08-25 02:50
Alpine does *not* come with glibc out of the box. There's a compat package described here https://wiki.alpinelinux.org/wiki/Running_glibc_programs

A recent CentOS *does* come with glibc and the at.h header. I've also tested in VMs running OpenIndiana and FreeBSD, neither using glibc, and the at.h header gets installed as expected.

**Comment by VorpalBlade** [comment] 2023-08-25 15:31
> Alpine does not come with glibc out of the box.

Exactly, they use musl libc instead, that is why I suggested taking a look at what they do.

**Comment by rdmark** [comment] 2023-08-27 19:08
For the record, Alpine is deprecating Berkeley DB with 3.13.0: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0 so it's getting ever so slightly more inconvenient to get started with netatalk.

The final BSD licensed BDB code is luckily available on github https://github.com/berkeleydb/libdb

To future proof this project we should consider moving to sqlite or similar. Just as a side note. :)

**Comment by rdmark** [comment] 2023-08-27 20:20
Seems to work as expected on Alpine. Took the opportunity to update the wiki with installation instructions: https://github.com/Netatalk/netatalk/wiki/Installation-Notes#alpine-linux

**Closed** 2023-08-27 20:27 UTC
Labels: target-release-2.2
